version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: it2
      POSTGRES_PASSWORD: 2222
      POSTGRES_DB: unique_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
